function b = rf_downconvert_lpf(fs,fpass,fstop)
%RF_DOWNCONVERT_LPF

% MATLAB Code
% Generated by MATLAB(R) 24.2 and DSP System Toolbox 24.2.
% Generated on: 23-Nov-2024 11:37:20

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Dpass = 0.057501127785;  % Passband Ripple
Dstop = 0.0001;          % Stopband Attenuation
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([fpass, fstop]/(fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});

% [EOF]
